threefoldtech/threefold_connect

- app/lib/screens/MainScreen.dart
- app/lib/services/3botService.dart
Fixed app build number mismatch and error
> Fixed app build number mismatch and error

- app/lib/AppConfig.dart
- app/lib/AppConfigLocal.template
- app/lib/screens/MainScreen.dart
Added missing to check to make sure people get the correct error message when our servers are down or they can't resolve our address.
> Development internet

- app/lib/screens/HomeScreen.dart
- app/lib/screens/MainScreen.dart
Now only tracks time spend when the app is paused.
> V1.4.3 pinfix

- app/lib/Apps/Wallet/walletWidget.dart
- app/lib/screens/ScanScreen.dart
- app/lib/services/fingerprintService.dart
Fixed black screen when keyboard was shown.
> Fixed keyboard on QR scan

- app/lib/screens/PreferenceScreen.dart
- app/lib/widgets/PreferenceDialog.dart
> small fixes

- app/lib/events/new_login_event.dart
- app/lib/models/login.dart
- app/lib/models/scope.dart
- app/lib/screens/home_screen.dart
- app/lib/screens/login_screen.dart
- app/lib/screens/preference_screen.dart
- app/lib/screens/recover_screen.dart
- app/lib/screens/registered_screen.dart
- app/lib/screens/unregistered_screen.dart
- app/lib/services/socket_service.dart
- app/lib/services/uni_link_service.dart
- app/lib/services/user_service.dart
- app/lib/widgets/preference_dialog.dart
- example/public/config.prod.js
- example/public/config.staging.js
- example/src/services/threebotService.js
- example/src/views/profile/profile.html
- example/src/views/profile/profile.js
- frontend/src/views/EmbeddedLogin/EmbeddedLogin.js
- frontend/src/views/Initial/Initial.js
- frontend/src/views/Login/Login.js
- frontend/src/views/VerifyEmail/VerifyEmail.js
> Scope rework (partial)

- app/pubspec.yaml
- frontend/src/store.js
- frontend/src/views/Initial/Initial.js
- Version bump
- Added redirection to the initial login page if you refresh the loginpage.
> Added redirect on refresh

- app/android/app/build_production
- app/android/gradle.properties
- app/android/gradle/wrapper/gradle-wrapper.properties
- app/build.sh
- app/lib/helpers/flags.dart
- app/lib/screens/main_screen.dart
- app/lib/screens/sign_screen.dart
- app/lib/widgets/preference_dialog.dart
- app/pubspec.yaml
- build the app with the latest versions flutter 3.13.0 and android 33
- Fix fetching the flags' values from flagsmith
- update the app version to 3.8.0
> Update the app to work with flutter 3.13.0

- app/lib/app_config.dart
- app/lib/apps/news/news.dart
- app/lib/apps/news/news_screen.dart
- app/lib/helpers/flags.dart
- app/lib/helpers/globals.dart
- app/lib/screens/wizard/web_view.dart
- app/pubspec.lock
- app/pubspec.yaml
- https://github.com/threefoldtech/threefold_connect_news/issues/5
https://github.com/user-attachments/assets/79a58cfc-c101-46a9-a7e0-06bd066c6a9e
> Link TFConnect news to threefold_io RSS 

- app/lib/screens/wallets/wallet_screen.dart
- app/lib/services/contact_service.dart
- app/lib/services/wallet_service.dart
- app/lib/widgets/wallets/add_edit_contact.dart
- app/lib/widgets/wallets/add_wallet.dart
- Fix loading empty wallets
- Fix loading empty contacts
- Fix loading after failure in adding contact
- Fix adding initial wallet
- #641 
- #642
> Fixing adding wallet and contacts for the first time

- app/lib/widgets/dao/show_result_dialog.dart
- app/lib/widgets/dao/vote_dialog.dart
- https://github.com/threefoldtech/threefold_connect/issues/637
> Add msg when user can't vote

- app/lib/screens/mobile_registration_screen.dart
- https://github.com/threefoldtech/threefold_connect/issues/653
https://github.com/user-attachments/assets/55163ff4-dd62-4323-a926-feb572cc9129
https://github.com/user-attachments/assets/31a3ea38-5189-49dc-8883-f705ac5aba54
> Handle stepper color

- app/lib/screens/wallets/transactions.dart
- https://github.com/threefoldtech/threefold_connect/issues/667
> Fix loading transactions

- app/lib/widgets/wallets/add_wallet.dart
- https://github.com/threefoldtech/threefold_connect/issues/673
- Get Hex seed of all existing wallets then compare them when hex seed of new wallet, If existing it means the wallet is duplicate.
> Fix adding existing wallet

- app/lib/screens/preference_screen.dart
- https://github.com/threefoldtech/threefold_connect/issues/639
> add face unlock in condition in changing icon

- app/lib/services/tfchain_service.dart
- app/lib/widgets/wallets/wallet_card.dart
- app/pubspec.lock
- app/pubspec.yaml
- Force the shared preferences package to be a working version.
- Wait for the balance to be transferred from the activation service to the wallet
- Fix getting the wallet balance after initialization
- #680
> Force shared preferences package to a working version

- app/lib/widgets/wallets/select_chain_widget.dart
- Set max width for tfchain btn
- Change tfchain btn size
- https://github.com/threefoldtech/threefold_connect/issues/688
- Change font size from mobile settings to large
- change font size to xlarge
> Set max width for tfchain btn

- app/lib/screens/wallets/send.dart
- app/lib/services/tfchain_service.dart
- https://github.com/threefoldtech/threefold_connect/issues/681
- send decimal/ int values.
https://github.com/user-attachments/assets/7c52b0ae-f7e1-48c2-866f-69c21cc9124e
> Fix sending decimal value to tfchain

- app/lib/screens/identity_verification_screen.dart
- app/lib/screens/wizard/web_view.dart
- app/lib/widgets/wizard/common_page.dart
- app/lib/widgets/wizard/terms_and_conditions.dart
- Add dialog with idenify security link
- update `WebView` component to be reusable by giving it title & link.
- https://github.com/threefoldtech/threefold_connect/issues/724
https://github.com/user-attachments/assets/de50e4de-e66f-4617-8525-d1ec1df13532
> add idenfy security link

- app/lib/providers/wallets_provider.dart
- app/lib/screens/wallets/wallet_screen.dart
- app/pubspec.lock
- app/pubspec.yaml
- https://github.com/threefoldtech/threefold_connect/issues/684
> Fix deleteWallet

- app/lib/screens/wallets/receive.dart
> Fix receive amount validation

- app/lib/services/tfchain_service.dart
> Open connection to tfchain before creating a farm

- app/lib/screens/wallets/receive.dart
- https://github.com/threefoldtech/threefold_connect/issues/752
> add decimal point in receive page

- app/lib/screens/preference_screen.dart
- app/lib/screens/recover_screen.dart
- app/lib/screens/unregistered_screen.dart
- app/lib/services/open_kyc_service.dart
- app/lib/services/wallet_service.dart
- backend/database.py
- backend/routes/misc.py
- backend/routes/users.py
> Support deleting account
